# Generated by Django 4.2.1 on 2023-10-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phd_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phd_student_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enroll', models.TextField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('phone', models.BigIntegerField(unique=True)),
                ('research_field', models.TextField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('profile_photo', models.ImageField(upload_to='phd_student/')),
            ],
        ),
    ]
