# Generated by Django 4.2.1 on 2023-11-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicAPI', '0002_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='files/')),
                ('type', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Phd_Student',
        ),
    ]
