# Generated by Django 4.2.1 on 2023-11-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicAPI', '0004_remove_file_id_alter_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='file',
            old_name='date',
            new_name='auto_date',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='date',
            new_name='auto_date',
        ),
    ]
