# Generated by Django 4.2.5 on 2023-09-16 15:04

from django.db import migrations

def create_default_courses(apps, schema_editor):
    Course = apps.get_model('IT_DEPARTMENT', 'Course')
    Course.objects.create(
        cid="COA5th",
        name="Computer Architecture and Organization",
        semester="5th",
        description="Architecture is important", # Assign the teacher to the course
    )
class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0004_alter_course_teacher'),
    ]

    operations = [
    ]
