# Generated by Django 4.2.5 on 2023-09-16 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0005_auto_20230916_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IT_DEPARTMENT.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='temporary',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
