# Generated by Django 4.2.5 on 2023-09-17 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0006_alter_course_description_alter_course_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('date', models.CharField(max_length=255)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IT_DEPARTMENT.course')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
