# Generated by Django 4.2.5 on 2023-09-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0007_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('valid', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
