# Generated by Django 4.2.5 on 2023-09-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0008_alerts_announcement_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alerts',
            new_name='Alert',
        ),
    ]
