# Generated by Django 4.2.5 on 2023-10-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0010_notes_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='cid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='cid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
