# Generated by Django 4.2.5 on 2023-10-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0011_assignment_cid_notes_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='deadline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
