# Generated by Django 4.2.1 on 2023-10-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phd_Student',
        ),
    ]
