# Generated by Django 4.2.1 on 2023-11-07 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('auto_date', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IT_DEPARTMENT.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('selection', models.CharField(choices=[('option1', 'Video'), ('option2', 'Blog'), ('option3', 'Other')], max_length=10)),
                ('tags', models.CharField(max_length=255)),
                ('auto_date', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IT_DEPARTMENT.teacher')),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
