# Generated by Django 4.2.6 on 2023-11-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0002_delete_phd_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('authors', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='education',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
