# Generated by Django 4.2.1 on 2023-11-11 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0002_events_tutorials_alter_announcement_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, upload_to='tutorials/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='image',
            field=models.ImageField(blank=True, default='temp', upload_to='tutorials/'),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='selection',
            field=models.CharField(blank=True, choices=[('option1', 'Video'), ('option2', 'Blog'), ('option3', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Phd_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enroll', models.TextField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('phone', models.BigIntegerField(blank=True)),
                ('research_field', models.TextField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('profile_photo', models.ImageField(upload_to='phd_student/')),
                ('teacher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='IT_DEPARTMENT.teacher')),
            ],
        ),
    ]
