# Generated by Django 4.2.1 on 2023-11-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0003_events_image_alter_events_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phd_student',
            name='phone',
            field=models.BigIntegerField(default=None),
        ),
    ]
