# Generated by Django 4.2.6 on 2023-11-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0003_research_teacher_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='about',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='researchs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
