# Generated by Django 4.2.1 on 2023-11-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0004_alter_phd_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phd_student',
            name='phone',
            field=models.BigIntegerField(blank=True, default=None),
        ),
    ]
