# Generated by Django 4.2.1 on 2023-11-11 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0005_alter_phd_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phd_student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IT_DEPARTMENT.teacher'),
        ),
    ]
