# Generated by Django 4.2.1 on 2023-11-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0006_alter_phd_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phd_student',
            name='phone',
        ),
        migrations.AddField(
            model_name='phd_student',
            name='alumni',
            field=models.BooleanField(default=False),
        ),
    ]
