# Generated by Django 4.2.1 on 2023-11-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0007_remove_phd_student_phone_phd_student_alumni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['semester']},
        ),
        migrations.AlterModelOptions(
            name='phd_student',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='selection',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('blog', 'Blog'), ('other', 'Other')], max_length=10),
        ),
    ]
