# Generated by Django 4.2.1 on 2023-11-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0008_alter_course_options_alter_phd_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phd_student',
            options={},
        ),
    ]
