# Generated by Django 4.2.6 on 2023-11-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0009_alter_phd_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
    ]
