# Generated by Django 4.2.1 on 2023-11-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0011_alter_events_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachereducation',
            name='Year',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='link',
            field=models.URLField(default='https://nitsri.ac.in/', max_length=255),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='selection',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('blog', 'Blog'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
