# Generated by Django 4.2.1 on 2023-11-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0012_alter_teachereducation_year_alter_tutorials_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachereducation',
            old_name='Year',
            new_name='year',
        ),
    ]
