# Generated by Django 4.2.1 on 2023-11-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0013_rename_year_teachereducation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='about',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
