# Generated by Django 4.2.1 on 2023-11-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_DEPARTMENT', '0014_alter_teacher_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
