# Generated by Django 4.2.8 on 2024-03-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_academics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='current_company',
            new_name='achievement',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='current_occupation',
            new_name='present_job',
        ),
        migrations.AddField(
            model_name='alumni',
            name='previous_jobs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
