# Generated by Django 4.2.6 on 2023-10-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_authuser_options_remove_authuser_date_joined_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
